--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/RankSystem
build-by-default: true
branches:
- PM3
- PM4
projects:
  RankSystem:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
        branch: master
      - src: LatamPMDevs/FormAPI/libFormAPI
        version: ^2.1.0
      - src: poggit/libasynql/libasynql
        version: ^4.0.0
...
