--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IvanCraft623/RankSystem
build-by-default: true
branches:
- PM3
- PM4
projects:
  RankSystem:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.0
...
