---
name: RankSystem
author: IvanCraft623
version: 1.0.0
main: IvanCraft623\RankSystem\RankSystem
api: "4.4.0"
softdepend:
  - ScoreHud
permissions:
  ranksystem.commands:
    default: op
    description: "Allows use ranks commands"
...
